//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iPhoneMessageExport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iPhoneMessageExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!--
        ///// Comments...
        /////
        /////
        /////--&gt;
        ///&lt;HTML&gt;
        ///&lt;HEAD&gt;
        ///&lt;TITLE&gt;iPhone Backup :: Message Export&lt;/TITLE&gt;
        ///&lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///&lt;script&gt;
        ///&lt;!--
        ///
        ///$(function() {
        ///    $(&apos;.timestamp&apos;).css({
        ///        &apos;top&apos; : &apos;50%&apos;,
        ///        &apos;margin-top&apos; : -$(&apos;.timestamp&apos;).outerHeight()/2
        ///    });
        ///});
        ///
        /////--&gt;
        ///&lt;/script&gt;
        ///&lt;STYLE TYPE=&quot;text/css&quot;&gt;
        ///@import url(https://fonts.googleapis.com/css?family=Lato|Lato:300);
        ///
        ///body {
        ///	margin: 0 auto;
        ///	padding: 1.5em 0;
        ///	wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTMLHeaders {
            get {
                return ResourceManager.GetString("HTMLHeaders", resourceCulture);
            }
        }
    }
}
